title: TestWhere.blog
author:
  name: Justas Laužadis
  email: "justas.testwhere@gmail.com"

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Build clarity and quality will follow.

remote_theme: jekyll/minima@2.5.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10

include:
  - _pages

minima:
  nav_pages:
    - _pages/recommended-sources.md
    - _pages/about.md

google_analytics: G-DQWGHDTX0W

defaults:
  - scope:
      path: ""
      type: posts
    values:
      image: logo.jpg
  - scope:
      path: ""
      type: pages
    values:
      image: logo.jpg