title: Test-Where.github.io
author:
  name: Justas Lauzadis
  email: justas.testwhere@gmail.com

theme: minima

header_pages:
  - about.md

minima:
  - { platform: github,         user_url: "https://github.com/test-where/test-where.github.io" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/justas.lauzadis" }
